# GCP Cloud Build configuration for Aether Backend
# Builds Docker image and deploys to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aether-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aether-backend:latest'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aether-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aether-backend:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aether-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aether-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/aether-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/aether-backend:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build (15 minutes)
timeout: '900s'

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'aether-backend'

